vim.keymap.set("n", "<leader>tst", ":TestNearest -strategy=neovim<cr>")
vim.keymap.set("n", "<leader>tsf", ":TestFile -strategy=neovim<cr>")
vim.keymap.set("n", "<leader>tsa", ":TestSuite -strategy=neovim<cr>")
vim.keymap.set("n", "<leader>tsl", ":TestLast -strategy=neovim<cr>")
vim.keymap.set("n", "<leader>tsv", ":TestVisit<cr>")
